### ISSUE TITLE
How to:citing this package? for making video

### ISSUE THREAD

**Issue by HaoLi111** [bryanhanson/LindenmayeR#8]
I am planning to make a number of videos demonstrating the behavior of the L-system. How should I cite this package?

**Comment by HaoLi111** [comment]
Likely, the videos are to be posted on YouTube or Vimeo. I am also trying to render some other videos for fractals and modern visualizations for non-linear dynamical systems.

**Comment by bryanhanson** [comment]
You can do `citation("LindenmayeR") for the current version citation.
